CREATE TABLE {{schema}}.product_categories (
    category_id SERIAL PRIMARY KEY,
    product_category TEXT,
    inserted_at TIMESTAMP
);

CREATE TABLE {{schema}}.product_subcategories (
    subcategory_id SERIAL PRIMARY KEY,
    product_subcategory TEXT,
    inserted_at TIMESTAMP
);

CREATE TABLE {{schema}}.products (
    product_id SERIAL PRIMARY KEY,
    product TEXT,
    brand_name TEXT,
    category_id INT REFERENCES {{schema}}.product_categories(category_id),
    subcategory_id INT REFERENCES {{schema}}.product_subcategories(subcategory_id),
    inserted_at TIMESTAMP
);

CREATE TABLE {{schema}}.customers (
    customer_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_firstname TEXT,
    customer_lastname TEXT,
    customer_gender TEXT,
    customer_shirtsize TEXT,
    customer_email TEXT UNIQUE,
    customer_phone TEXT,
    customer_age INT,
    customer_address TEXT,
    address_details TEXT,
    customer_city TEXT,
    customer_state TEXT,
    inserted_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

-- Unique constraint for deduplication
    CONSTRAINT unique_customer_identity UNIQUE (
        customer_email
    )
);

CREATE TABLE {{schema}}.stores (
    store_id SERIAL PRIMARY KEY,
    store_type TEXT,
    store_street TEXT,
    store_city TEXT,
    store_state TEXT,
    inserted_at TIMESTAMP
);

CREATE TABLE {{schema}}.employees (
    employee_id SERIAL PRIMARY KEY,
    employee_firstname TEXT,
    employee_lastname TEXT,
    employee_email TEXT,
    employee_skill TEXT,
    employee_education TEXT,
    inserted_at TIMESTAMP
);

CREATE TABLE {{schema}}.payment_methods (
    payment_method_id SERIAL PRIMARY KEY,
    payment_method TEXT,
    inserted_at TIMESTAMP
);

CREATE TABLE {{schema}}.shipping_methods (
    shipping_method_id SERIAL PRIMARY KEY,
    shipping_method TEXT,
    inserted_at TIMESTAMP
);

CREATE TABLE {{schema}}.currency_rates (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    currency VARCHAR(10) NOT NULL,
    to_euro FLOAT,
    to_isl FLOAT,
    date DATE NOT NULL,
    inserted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    -- Unique constraint for deduplication currency_date
    CONSTRAINT unique_currency_date UNIQUE(
        currency, date)
);

CREATE TABLE {{schema}}.sales (
    transaction_id SERIAL PRIMARY KEY,
    tmstmp TIMESTAMP,
    product_id INT REFERENCES {{schema}}.products(product_id),
    customer_id INT REFERENCES {{schema}}.customers(customer_id),
    store_id INT REFERENCES {{schema}}.stores(store_id),
    employee_id INT REFERENCES {{schema}}.employees(employee_id),
    payment_method_id INT REFERENCES {{schema}}.payment_methods(payment_method_id),
    shipping_method_id INT REFERENCES {{schema}}.shipping_methods(shipping_method_id),
    product_price NUMERIC,
    currency TEXT,
    coupon_discount NUMERIC,
    quantity_sold INT,
    total_amount NUMERIC,
    total_costs NUMERIC,
    sales_channel TEXT,
    store_website TEXT,
    supplier TEXT,
    inserted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    -- Unique constraint for deduplication
    CONSTRAINT unique_customer_timestamp UNIQUE (
        customer_id, tmstmp
    )
);