services:
  # Main business DB
  postgres:
    image: postgres:15
    container_name: postgres_db_2
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: sport_gear_store
    volumes:
      - postgres_data_2:/var/lib/postgresql/data

  # S3 imitation with MinIO
  minio:
    image: minio/minio
    container_name: minio_2
    ports:
      - "9110:9000"  # S3 API
      - "9111:9001"  # Web UI
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data_2:/data

  # Airflow metadata DB
  airflow-db:
    image: postgres:15
    container_name: airflow_db_2
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - airflow_postgres_data_2:/var/lib/postgresql/data

  # Airflow Scheduler
  airflow-scheduler:
    image: apache/airflow:2.8.1
    depends_on:
      - airflow-db
    environment:
      ENV: airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db/airflow
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      PYTHONPATH: /opt/airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ./etl:/opt/airflow/etl
      - ./data_generator:/opt/airflow/data_generator
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./configs:/opt/airflow/configs
      - ./envs/.env.airflow:/opt/airflow/.env.airflow
      - ./db:/opt/airflow/db
    command: scheduler

  # Airflow Webserver
  airflow-webserver:
    image: apache/airflow:2.8.1
    depends_on:
      - airflow-scheduler
    ports:
      - "8080:8080"
    environment:
      ENV: airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db/airflow
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      PYTHONPATH: /opt/airflow
      
    volumes:
      - ./dags:/opt/airflow/dags
      - ./etl:/opt/airflow/etl
      - ./data_generator:/opt/airflow/data_generator
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./configs:/opt/airflow/configs
      - ./envs/.env.airflow:/opt/airflow/.env.airflow
      - ./db:/opt/airflow/db
    command: webserver

volumes:
  postgres_data_2:
  minio_data_2:
  airflow_postgres_data_2: